### ISSUE TITLE
How TENxIO inteoperates with Bioc classes?

### ISSUE THREAD

**Issue by drighelli** [waldronlab/TENxIO#1]
Hi Marcel,

very nice work!

This is more of a question than an issue itself.

How do the TENxIO classes interoperate with the existing Bioc classes? like SingleCellExperiment etc?

In my case, I want to use your class to create a SingleCellExperiment with two assays one for the GEX and one for the ATAC, starting from a cellranger ARC output directory.

Thanks,
Dario

**Comment by LiNk-NY** [comment]
Hi Dario, @drighelli 
Thanks for the question. See the vignette for more details but generally, you
recognize the file type you are working with, e.g., use `TENxH5` for hdf5 files.
Then you can `import` using the import method. 
If you have a direct web link to the file on 10X, I can provide more assistance. 

Best regards,
Marcel

**Comment by drighelli** [comment]
Hi Marcel,

thanks for the answer... I'm surely wrong, but I was asking that because reading the vignette gives me the idea that in this package there are several new classes for handling the 10x data... without mentioning the existing "Experiment" classes.

Because we exhaustively use these classes, it would be useful to have a function returning the data in "Experiment" classes format, for third parties usage... Is it there and am I missing it?

Thanks again!

**Comment by LiNk-NY** [comment]
Yes, it's a two step process. One recognizes the file type and does not load the data and the other loads the data and uses a Bioconductor representation. 

> it would be useful to have a function returning the data in "Experiment" classes format, for third parties usage

This is what the import method does. I can make this more clear in the vignette. 

Thanks!

**Comment by drighelli** [comment]
oh ok, sorry I didn't see the import method.

looking forward to working with this package and helping to implement the 10x Visium part.
