### ISSUE TITLE
TENxFileList creates SummarizedExperiment assay

### ISSUE THREAD

**Issue by gdagstn** [waldronlab/TENxIO#2]
Hi, 

Thanks for developing this package! It's quite timely since `Matrix` has updated and broken a couple functions for reading 10X data.

Is there a specific reason why the assay class in `SingleCellExperiment` is a `SummarizedExperiment` instead of a count matrix? 

It does not play nice with several other functions that expect `class(counts(sce))` to be a `matrix` of some sort. The `assay` of the `SummarizedExperiment` contains the correct data type, but I don't think this is how many other packages expect to fetch the data:

```{r}
fl <- system.file(
    "extdata", "pbmc_granulocyte_sorted_3k_ff_bc_ex_matrix.tar.gz",
    package = "TENxIO", mustWork = TRUE
)

con <- TENxFileList(fl)
sce <- import(con)

class(counts(sce))

  [1] "SummarizedExperiment"
  attr(,"package")
  [1] "SummarizedExperiment"

class(assay(counts(sce))) 

  [1] "dgCMatrix"
  attr(,"package")
  [1] "Matrix"
```

Thanks!

edit to add: this is using TENxIO v 1.0.0

**Comment by LiNk-NY** [comment]
Hi Giuseppe, @gdagstn 
Thank you for reporting this. I have fixed the bug in the devel version (`1.1.2`) and will port to release (`1.0.1`). 
Best regards,
Marcel
